spring.application.name=SpringSecurityDemo
spring.security.user.name = pavan
spring.security.user.password=alpha

spring.datasource.url=jdbc:postgresql://localhost:5432/SpringSecurity
spring.datasource.username = postgres
spring.datasource.password = 123
