spring.application.name=SpringSecurityDemo
spring.security.user.name = pavan
spring.security.user.password=alpha

spring.datasouce.url=jdbc:postgres://localhost:5432/SpringSecurity
spring.datasource.username = postgres
spring.datasource.password = Pavan@2001
